windowrule = opacity 0.0 override 0.0 override, match:class ^(xwaylandvideobridge)$
windowrule = no_anim true, match:class ^(xwaylandvideobridge)$
windowrule = no_initial_focus true, match:class ^(xwaylandvideobridge)$
windowrule = max_size 1 1, match:class ^(xwaylandvideobridge)$
windowrule = no_blur true, match:class ^(xwaylandvideobridge)$

windowrule = stay_focused true, match:class rofi

windowrule = float true, match:class jchat

windowrule = size 25% 25%, match:class music
windowrule = no_initial_focus true, match:class music
windowrule = float true, match:class music
windowrule = workspace special:media, match:class music
windowrule = move onscreen 75% 4%, match:class music
windowrule = opacity 1.0 override, match:class mpv

windowrule = opacity 1.0 override, match:title (.*)(YouTube)(.*)
windowrule = opacity 1.0 override, match:title (.*)(Twitch)(.*)
